import type { CateringEvent } from '@/types'

export const MOCK_EVENTS: CateringEvent[] = [
  {
    id: '1',
    name: "Sofia's Birthday",
    client: 'Maria Garcia',
    date: '2026-03-15',
    guests: 40,
    type: 'Birthday',
    status: 'Confirmed',
    notes: 'Pink and gold theme',
    items: [],
    cost: 320,
    clientPrice: 480,
    markup: 40,
  },
  {
    id: '2',
    name: "Baby Shower — Emma",
    client: 'Laura Smith',
    date: '2026-03-28',
    guests: 25,
    type: 'Baby Shower',
    status: 'Planning',
    notes: '',
    items: [],
    cost: 210,
    clientPrice: 300,
    markup: 40,
  },
  {
    id: '3',
    name: "Ana & Tom Wedding",
    client: 'Ana Rivera',
    date: '2026-04-10',
    guests: 120,
    type: 'Wedding',
    status: 'Confirmed',
    notes: 'Rustic style',
    items: [],
    cost: 850,
    clientPrice: 1200,
    markup: 41,
  },
]